DROP TABLE COUNSEL_RESERVATION;
DROP TABLE STUDENT_DETAIL;
DROP TABLE MEMBER_LOCK;
DROP TABLE MEMBER_MEMO
DROP TABLE COUNSELOR_PROFILE;
DROP TABLE POST_COMMENT;
DROP TABLE COUNSEL_CATEGORY;
DROP TABLE BOARD_POST;
DROP TABLE COUNSELOR_INVITE;
DROP TABLE MEMBER;
DROP TABLE CLASS;

-- 5월 27일 수정 및 추가해야 할것
-- MEMBER 테이블에 STATUS 변경 (현재 CHECK 제약조건하고 DEFAULT 없음)
--                ROLE_CODE 변경 (현재 CHECK 제약조건하고 DEFAULT 없음)
-- BOARD_POST 테이블에 STATUS 변경 (현재 CHECK 제약조건하고 DEFAULT 없음)
-- COUNSELOR_INVITE 테이블에 INVITE_STATUS 변경 (현재 CHECK 제약조건하고 DEFAULT 없음)
-- COUNSELOR_PROFILE 테이블에 STATUS 변경(현재 CHECK 제약조건하고 DEFAULT 없음)
-- FILE_ATTACHMENT 테이블 추가해야 함
-- COUNSEL_LOG 테이블 추가해야 함
-- 각 제약조건별 제약조건명 추가해야 함
-- 각 SEQUENCE 생성해야 함

--반 테이블
CREATE TABLE CLASS (
  CLASS_NO NUMBER PRIMARY KEY,
  CLASS_NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL CHECK(STATUS IN('Y', 'N')),
  CREATED_AT DATE DEFAULT SYSDATE,
  UPDATED_AT DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN CLASS.CLASS_NO IS '반번호';
COMMENT ON COLUMN CLASS.CLASS_NAME IS '반이름';
COMMENT ON COLUMN CLASS.DESCRIPTION IS '반설명';
COMMENT ON COLUMN CLASS.STATUS IS '사용상태';
COMMENT ON COLUMN CLASS.CREATED_AT IS '생성일';
COMMENT ON COLUMN CLASS.UPDATED_AT IS '수정일';

-- 회원 테이블
CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL,
  USER_PWD VARCHAR2(200) NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(300),
  ROLE_CODE VARCHAR2(20) NOT NULL,
  STATUS VARCHAR2(20),
  CREATED_AT DATE,
  UPDATED_AT DATE,
  CLASS_NO NUMBER,
  FOREIGN KEY(CLASS_NO) REFERENCES CLASS(CLASS_NO)
);

COMMENT ON COLUMN MEMBER.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '사용자아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '사용자비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '사용자이름';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ROLE_CODE IS '권한코드';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값';
COMMENT ON COLUMN MEMBER.CREATED_AT IS '생성일';
COMMENT ON COLUMN MEMBER.UPDATED_AT IS '수정일';
COMMENT ON COLUMN MEMBER.CLASS_NO IS '반번호';

--상담사링크관리 테이블
CREATE TABLE COUNSELOR_INVITE (
  INVITE_NO NUMBER PRIMARY KEY,
  INVITE_NAME VARCHAR2(20) NOT NULL,
  INVITE_EMAIL VARCHAR2(100),
  INVITE_TOKEN VARCHAR2(50),
  INVITE_SENT_AT DATE,
  INVITE_EXPIRED_AT DATE,
  INVITE_STATUS VARCHAR2(20),
  USER_NO NUMBER,
  FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_NO IS '식별번호';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_NAME IS '상담사이름';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_EMAIL IS '상담사이메일';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_TOKEN IS '토큰';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_SENT_AT IS '토큰생성시간';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_EXPIRED_AT IS '토큰만료시간';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_STATUS IS '상태';
COMMENT ON COLUMN COUNSELOR_INVITE.USER_NO IS '사용자번호';

-- 게시글 테이블
CREATE TABLE BOARD_POST (
  POST_NO NUMBER PRIMARY KEY,
  WRITER_NO NUMBER,
  POST_TYPE VARCHAR2(10) NOT NULL,
  CATEGORY VARCHAR2(30) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  STATUS VARCHAR2(1),
  VIEW_COUNT NUMBER
);
COMMENT ON COLUMN BOARD_POST.POST_NO IS '게시글번호';
COMMENT ON COLUMN BOARD_POST.WRITER_NO IS '작성자회원번호';
COMMENT ON COLUMN BOARD_POST.POST_TYPE IS '게시글타입';
COMMENT ON COLUMN BOARD_POST.CATEGORY IS '게시글 카테고리';
COMMENT ON COLUMN BOARD_POST.TITLE IS '글제목';
COMMENT ON COLUMN BOARD_POST.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD_POST.CREATED_AT IS '작성일';
COMMENT ON COLUMN BOARD_POST.UPDATED_AT IS '수정일';
COMMENT ON COLUMN BOARD_POST.STATUS IS '상태값';
COMMENT ON COLUMN BOARD_POST.VIEW_COUNT IS '조회수';

-- 상담 카테고리 테이블
CREATE TABLE COUNSEL_CATEGORY (
  CATEGORY_NO NUMBER PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN COUNSEL_CATEGORY.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSEL_CATEGORY.CATEGORY_NAME IS '상담카테고리명';

INSERT INTO COUNSEL_CATEGORY VALUES(1, '취업');
INSERT INTO COUNSEL_CATEGORY VALUES(2, '진로');
INSERT INTO COUNSEL_CATEGORY VALUES(3, '수강');

-- 댓글 테이블
CREATE TABLE POST_COMMENT (
  COMMENT_NO NUMBER PRIMARY KEY,
  POST_NO NUMBER NOT NULL,
  WRITER_NO NUMBER NOT NULL,
  CONTENT VARCHAR2(1000),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y','N')),
  FOREIGN KEY(POST_NO) REFERENCES BOARD_POST(POST_NO)
);

COMMENT ON COLUMN POST_COMMENT.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN POST_COMMENT.POST_NO IS '게시글번호';
COMMENT ON COLUMN POST_COMMENT.WRITER_NO IS '작성자번호';
COMMENT ON COLUMN POST_COMMENT.CONTENT IS '댓글내용';
COMMENT ON COLUMN POST_COMMENT.CREATED_AT IS '생성일';
COMMENT ON COLUMN POST_COMMENT.UPDATED_AT IS '수정일';
COMMENT ON COLUMN POST_COMMENT.STATUS IS '상태값 Y/N';

-- 직원관리테이블
CREATE TABLE COUNSELOR_PROFILE (
  COUNSEL_NO NUMBER PRIMARY KEY,
  CATEGORY_NO NUMBER NOT NULL,
  PROFILE_IMG_PATH VARCHAR2(500),
  BIO VARCHAR2(300),
  STATUS VARCHAR2(10),
  USER_NO NUMBER,
  FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
  FOREIGN KEY(CATEGORY_NO) REFERENCES COUNSEL_CATEGORY(CATEGORY_NO)
);


COMMENT ON COLUMN COUNSELOR_PROFILE.COUNSEL_NO IS '상담사번호';
COMMENT ON COLUMN COUNSELOR_PROFILE.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSELOR_PROFILE.PROFILE_IMG_PATH IS '프로필사진경로';
COMMENT ON COLUMN COUNSELOR_PROFILE.BIO IS '사원정보';
COMMENT ON COLUMN COUNSELOR_PROFILE.STATUS IS '비고';
COMMENT ON COLUMN COUNSELOR_PROFILE.USER_NO IS '사용자번호';

-- 메모 테이블
CREATE TABLE MEMBER_MEMO (
  MEMO_NO NUMBER PRIMARY KEY,
  USER_NO NUMBER NOT NULL,
  USER_MEMO CLOB,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
  FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN MEMBER_MEMO.MEMO_NO IS '메모번호';
COMMENT ON COLUMN MEMBER_MEMO.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER_MEMO.USER_MEMO IS '회원메모';
COMMENT ON COLUMN MEMBER_MEMO.CREATED_AT IS '메모생성일';
COMMENT ON COLUMN MEMBER_MEMO.UPDATED_AT IS '메모수정일';

-- 계정잠금 테이블
CREATE TABLE MEMBER_LOCK (
  USER_NO NUMBER PRIMARY KEY,
  FAIL_COUNT NUMBER,
  IS_LOCKED VARCHAR2(1) DEFAULT 'Y' CHECK (IS_LOCKED IN ('Y','N')),
  LOCKED_AT DATE DEFAULT SYSDATE NOT NULL,
  LAST_FAIL_AT DATE DEFAULT SYSDATE NOT NULL,
  FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN MEMBER_LOCK.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER_LOCK.FAIL_COUNT IS '로그인실패횟수';
COMMENT ON COLUMN MEMBER_LOCK.IS_LOCKED IS '계정잠금여부';
COMMENT ON COLUMN MEMBER_LOCK.LOCKED_AT IS '잠금발생시간';
COMMENT ON COLUMN MEMBER_LOCK.LAST_FAIL_AT IS '마지막로그인실패시간';

-- 학생 테이블
CREATE TABLE STUDENT_DETAIL (
  STUDENT_NO NUMBER PRIMARY KEY,
  COUNSELOR_NO NUMBER,
  PARENT_PHONE VARCHAR2(20),
  CONSULT_STATUS VARCHAR2(1) DEFAULT 'N' CHECK(CONSULT_STATUS IN('Y', 'N')),
  STUDENT_STATUS VARCHAR2(20) DEFAULT '재학' CHECK(STUDENT_STATUS IN('재학', '휴학', '퇴학')),
  CREATED_AT DATE DEFAULT SYSDATE,
  UPDATED_AT DATE DEFAULT SYSDATE,
  FOREIGN KEY (COUNSELOR_NO) REFERENCES COUNSELOR_PROFILE(COUNSEL_NO)
);

COMMENT ON COLUMN STUDENT_DETAIL.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN STUDENT_DETAIL.COUNSELOR_NO IS '담당상담사번호';
COMMENT ON COLUMN STUDENT_DETAIL.PARENT_PHONE IS '학부모연락처';
COMMENT ON COLUMN STUDENT_DETAIL.CONSULT_STATUS IS '상담진행여부';
COMMENT ON COLUMN STUDENT_DETAIL.STUDENT_STATUS IS '학생상태';
COMMENT ON COLUMN STUDENT_DETAIL.CREATED_AT IS '생성일';
COMMENT ON COLUMN STUDENT_DETAIL.UPDATED_AT IS '수정일';

-- 예약 테이블
CREATE TABLE COUNSEL_RESERVATION (
  RESERVATION_NO NUMBER PRIMARY KEY,
  STUDENT_NO NUMBER NOT NULL,
  CATEGORY_NO NUMBER NOT NULL,
  CONSULT_DATE DATE DEFAULT SYSDATE NOT NULL,
  INQUIRY_CONTENT CLOB NOT NULL,
  RESERVATION_STATUS VARCHAR2(20) DEFAULT 'RESERVED' CHECK(RESERVATION_STATUS IN ('APPLIED', 'CANCELED', 'RESERVED', 'COMPLETED')), 
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  COUNSEL_NO NUMBER NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE NOT NULL,
  FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT_DETAIL(STUDENT_NO),
  FOREIGN KEY (COUNSEL_NO) REFERENCES COUNSELOR_PROFILE(COUNSEL_NO)
);

COMMENT ON COLUMN COUNSEL_RESERVATION.RESERVATION_NO IS '예약번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.CONSULT_DATE IS '상담일시';
COMMENT ON COLUMN COUNSEL_RESERVATION.INQUIRY_CONTENT IS '문의내용';
COMMENT ON COLUMN COUNSEL_RESERVATION.RESERVATION_STATUS IS '예약상태';
COMMENT ON COLUMN COUNSEL_RESERVATION.CREATED_AT IS '생성일';
COMMENT ON COLUMN COUNSEL_RESERVATION.COUNSEL_NO IS '상담사번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.UPDATED_AT IS '수정일';

COMMIT;