DELETE 
FROM BOARD_POST
WHERE STATUS = 'N';
COMMIT;

SELECT SEARCH_CONDITION 
FROM USER_CONSTRAINTS 
WHERE CONSTRAINT_NAME = 'CK_TARGET_TYPE';

ALTER TABLE FILE_ATTACHMENT DROP CONSTRAINT CK_TARGET_TYPE; 
-- 제약조건 이름은 확인 후 수정

ALTER TABLE FILE_ATTACHMENT 
ADD CONSTRAINT CK_TARGET_TYPE 
CHECK (TARGET_TYPE IN ('NOTICE', 'POST', 'NEWS', 'STUDENT'));

SELECT * FROM FILE_ATTACHMENT WHERE TARGET_NO = 23;

BEGIN
    -- 1. 수강생 게시글 50개 생성
    INSERT INTO BOARD_POST (POST_NO, POST_TYPE, CATEGORY, TITLE, CONTENT, WRITER_NO, CREATED_AT, STATUS)
    SELECT SEQ_POST_NO.NEXTVAL, 'STUDENT', '수강생 게시판', '수강생 게시글 번호 ' || LEVEL, '내용 ' || LEVEL, TRUNC(DBMS_RANDOM.VALUE(7, 12)), SYSDATE, 'Y'
    FROM DUAL CONNECT BY LEVEL <= 50;

    -- 2. 공지사항 30개 생성
    INSERT INTO BOARD_POST (POST_NO, POST_TYPE, CATEGORY, TITLE, CONTENT, WRITER_NO, CREATED_AT, STATUS)
    SELECT SEQ_POST_NO.NEXTVAL, 'NOTICE', '공지사항', '공지사항 게시글 번호 ' || LEVEL, '내용 ' || LEVEL, 1, SYSDATE, 'Y'
    FROM DUAL CONNECT BY LEVEL <= 30;

    -- 3. 자유게시판 107개 생성
    INSERT INTO BOARD_POST (POST_NO, POST_TYPE, CATEGORY, TITLE, CONTENT, WRITER_NO, CREATED_AT, STATUS)
    SELECT SEQ_POST_NO.NEXTVAL, 
    'POST', '자유게시판', '자유 게시글 번호 ' || LEVEL, '내용 ' || LEVEL, 
    TRUNC(DBMS_RANDOM.VALUE(2, 12)), SYSDATE, 'Y'
    FROM DUAL CONNECT BY LEVEL <= 107;

    COMMIT;
END;


UPDATE FILE_ATTACHMENT 
SET STATUS = 'N' 
WHERE TARGET_NO = 315 
  AND FILE_NO != 34;

-- 다른 게시글(311, 317, 319 등)도 동일하게 수행하세요.
-- 311번의 경우 FILE_NO 312번만 살리고 나머지는 N 처리
UPDATE FILE_ATTACHMENT SET STATUS = 'N' WHERE TARGET_NO = 311 AND FILE_NO != 312;

-- 2. 시퀀스 다시 생성 (1부터 시작)
CREATE SEQUENCE SEQ_POST_NO 
START WITH 1 
INCREMENT BY 1;

SELECT SEQ_POST_NO.NEXTVAL FROM DUAL;