CREATE TABLE FILE_ATTACHMENT (
    FILE_NO      NUMBER PRIMARY KEY,         -- 파일번호 (PK)
    TARGET_NO    NUMBER NOT NULL,            -- 원본게시글식별번호
    TARGET_TYPE  VARCHAR2(20) NOT NULL,      -- 원본게시글 타입 (NOTICE/POST)
    ORIGIN_NAME  VARCHAR2(300) NOT NULL,     -- 원본파일명
    SAVE_NAME    VARCHAR2(300) NOT NULL,     -- 저장파일명 (UUID)
    FILE_PATH    VARCHAR2(500) NOT NULL,     -- 저장폴더경로
    CREATED_AT   DATE DEFAULT SYSDATE,       -- 업로드일
    UPDATED_AT   DATE DEFAULT SYSDATE,       -- 수정일
    STATUS       VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')), -- 상태값 (Y/N)
    FILE_LEVEL   VARCHAR2(1)                 -- 파일레벨 (1/2)
);

-- 시퀀스 생성 (파일번호 자동 증가용)
CREATE SEQUENCE SEQ_FNO NOCACHE;

COMMENT ON COLUMN FILE_ATTACHMENT.FILE_NO IS '파일 번호';
COMMENT ON COLUMN FILE_ATTACHMENT.TARGET_NO IS '게시글 번호';
COMMENT ON COLUMN FILE_ATTACHMENT.TARGET_TYPE IS '게시판 유형 (POST, NOTICE 등)';
COMMENT ON COLUMN FILE_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN FILE_ATTACHMENT.SAVE_NAME IS '저장 파일명';
COMMENT ON COLUMN FILE_ATTACHMENT.FILE_PATH IS '파일 저장 경로';
COMMENT ON COLUMN FILE_ATTACHMENT.CREATED_AT IS '업로드 일';
COMMENT ON COLUMN FILE_ATTACHMENT.UPDATED_AT IS '수정 일자';
COMMENT ON COLUMN FILE_ATTACHMENT.STATUS IS '삭제 여부 (Y:유지, N:삭제)';
COMMENT ON COLUMN FILE_ATTACHMENT.FILE_LEVEL IS '파일 구분 (1:썸네일, 2:일반)';


-- 계정 생성
CREATE USER SEMI IDENTIFIED BY SEMI;
-- 권한 부여
GRANT CONNECT, RESOURCE TO SEMI;
COMMIT;