DELETE 
FROM BOARD_POST
WHERE STATUS = 'N';
COMMIT;

SELECT SEARCH_CONDITION 
FROM USER_CONSTRAINTS 
WHERE CONSTRAINT_NAME = 'CK_TARGET_TYPE';

ALTER TABLE FILE_ATTACHMENT DROP CONSTRAINT CK_TARGET_TYPE; 
-- 제약조건 이름은 확인 후 수정

ALTER TABLE FILE_ATTACHMENT 
ADD CONSTRAINT CK_TARGET_TYPE 
CHECK (TARGET_TYPE IN ('NOTICE', 'POST', 'NEWS', 'STUDENT'));

SELECT * FROM FILE_ATTACHMENT WHERE TARGET_NO = 23;

--0. 게시글 랜덤생성
BEGIN
  FOR i IN 1..107 LOOP
    INSERT INTO BOARD_POST (
                POST_NO, 
                POST_TYPE, 
                CATEGORY, 
                TITLE, 
                CONTENT, 
                WRITER_NO, 
                CREATED_AT, 
                STATUS)
    VALUES (SEQ_POST_NO.NEXTVAL, 
    'POST', 
    '자유', 
    '자유게시판 게시글 번호 ' || i, 
    '이것은 자동으로 생성된 ' || i || '번째 게시글 내용입니다.', 
    FLOOR(DBMS_RANDOM.VALUE(1, 11)), 
    SYSDATE, 
    'Y');
  END LOOP;
  COMMIT;
END;

SELECT SEQ_POST_NO.NEXTVAL FROM DUAL;
SELECT MAX(POST_NO) FROM BOARD_POST;

UPDATE BOARD_POST 
SET CATEGORY = '자유', 
    WRITER_NO = FLOOR(DBMS_RANDOM.VALUE(2, 12));
COMMIT;

-- 1. 게시글과 연결된 첨부파일 데이터 먼저 삭제
DELETE FROM FILE_ATTACHMENT;
-- 2. 게시글 데이터만 삭제
DELETE FROM BOARD_POST
-- 3. 시퀀스 1번부터 다시 시작하도록 초기화
DROP SEQUENCE SEQ_POST_NO;
CREATE SEQUENCE SEQ_POST_NO START WITH 1 INCREMENT BY 1;
COMMIT;

DROP SEQUENCE SEQ_POST_NO; (자식 테이블도 같이 삭제)

DROP SEQUENCE SEQ_POST_NO;