DROP TABLE COUNSEL_LOG CASCADE CONSTRAINTS;
DROP TABLE COUNSEL_RESERVATION CASCADE CONSTRAINTS;
DROP TABLE STUDENT_DETAIL CASCADE CONSTRAINTS;
DROP TABLE MEMBER_LOCK CASCADE CONSTRAINTS;
DROP TABLE MEMBER_MEMO CASCADE CONSTRAINTS;
DROP TABLE COUNSELOR_PROFILE CASCADE CONSTRAINTS;
DROP TABLE FILE_ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE POST_COMMENT CASCADE CONSTRAINTS;
DROP TABLE BOARD_POST CASCADE CONSTRAINTS;
DROP TABLE COUNSEL_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE COUNSELOR_INVITE CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE CLASS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CLASS_NO;
DROP SEQUENCE SEQ_USER_NO;
DROP SEQUENCE SEQ_INVITE_NO;
DROP SEQUENCE SEQ_POST_NO;
DROP SEQUENCE SEQ_CATEGORY_NO;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_COUNSEL_NO;
DROP SEQUENCE SEQ_MEMO_NO;
DROP SEQUENCE SEQ_STUDENT_NO;
DROP SEQUENCE SEQ_RESERVATION_NO;
DROP SEQUENCE SEQ_FILE_NO;
DROP SEQUENCE SEQ_LOG_NO;

-- 5월 27일 수정 및 추가해야 할것
-- MEMBER 테이블에 STATUS 변경 (현재 CHECK 제약조건하고 DEFAULT 없음) (X)
--                ROLE_CODE 변경 (현재 CHECK 제약조건하고 DEFAULT 없음) (X)
-- BOARD_POST 테이블에 STATUS 변경 (현재 CHECK 제약조건하고 DEFAULT 없음) (X)
-- COUNSELOR_INVITE 테이블에 INVITE_STATUS 변경 (현재 CHECK 제약조건하고 DEFAULT 없음) (X)
-- COUNSELOR_PROFILE 테이블에 STATUS 변경(현재 CHECK 제약조건하고 DEFAULT 없음) (X)
-- FILE_ATTACHMENT 테이블 추가해야 함 (O)
-- COUNSEL_LOG 테이블 추가해야 함 (O)
-- 각 제약조건별 제약조건명 추가해야 함 (X)
-- 각 SEQUENCE 생성해야 함 (X)

-- 5월 29일 수정
-- 모든테이블 추가 완료
-- 모든테이블 수정 완료

-- 테이블 시퀀스
CREATE SEQUENCE SEQ_CLASS_NO NOCACHE;
CREATE SEQUENCE SEQ_USER_NO NOCACHE;
CREATE SEQUENCE SEQ_INVITE_NO NOCACHE;
CREATE SEQUENCE SEQ_POST_NO NOCACHE;
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;
CREATE SEQUENCE SEQ_COUNSEL_NO NOCACHE;
CREATE SEQUENCE SEQ_MEMO_NO NOCACHE;
CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION_NO NOCACHE;
CREATE SEQUENCE SEQ_FILE_NO NOCACHE;
CREATE SEQUENCE SEQ_LOG_NO NOCACHE;


--반 테이블
CREATE TABLE CLASS (
  CLASS_NO NUMBER CONSTRAINT PK_CLASS_NO PRIMARY KEY,
  CLASS_NAME VARCHAR2(100) NOT NULL,
  DESCRIPTION VARCHAR2(500),
  STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL CONSTRAINT CK_CLASS_STATUS CHECK(STATUS IN('Y', 'N')),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN CLASS.CLASS_NO IS '반번호';
COMMENT ON COLUMN CLASS.CLASS_NAME IS '반이름';
COMMENT ON COLUMN CLASS.DESCRIPTION IS '반설명';
COMMENT ON COLUMN CLASS.STATUS IS '사용상태';
COMMENT ON COLUMN CLASS.CREATED_AT IS '생성일';
COMMENT ON COLUMN CLASS.UPDATED_AT IS '수정일';

INSERT INTO CLASS
VALUES(SEQ_CLASS_NO.NEXTVAL,'A반','2026년 5월 20일에 개설한 반입니다','Y',SYSDATE,SYSDATE);

INSERT INTO CLASS
VALUES(SEQ_CLASS_NO.NEXTVAL,'B반','2026년 5월 25일에 개설한 반입니다','Y',SYSDATE,SYSDATE);

INSERT INTO CLASS
VALUES(SEQ_CLASS_NO.NEXTVAL,'C반','2026년 5월 29일에 개설한 반입니다','Y',SYSDATE,SYSDATE);

INSERT INTO CLASS
VALUES(SEQ_CLASS_NO.NEXTVAL,'D반','2026년 6월 1일에 개설한 반입니다','N',SYSDATE,SYSDATE);


-- 회원 테이블
CREATE TABLE MEMBER (
  USER_NO NUMBER CONSTRAINT PK_USER_NO PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL CONSTRAINT UQ_USER_ID UNIQUE,
  USER_PWD VARCHAR2(200) NOT NULL,
  USER_NAME VARCHAR2(20) NOT NULL,
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(100) NOT NULL,
  ADDRESS VARCHAR2(300),
  ROLE_CODE VARCHAR2(20) DEFAULT 'STUDENT' NOT NULL CONSTRAINT CK_MEMBER_ROLE_CODE CHECK (ROLE_CODE IN('STUDENT', 'COUNSELOR', 'INSTRUCTOR', 'ADMIN')),
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL  CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN('PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED', 'WITHDRAWN')),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  CLASS_NO NUMBER,
  CONSTRAINT FK_MEMBER_CLASS FOREIGN KEY(CLASS_NO) REFERENCES CLASS(CLASS_NO)
);

COMMENT ON COLUMN MEMBER.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '사용자아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '사용자비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '사용자이름';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ROLE_CODE IS '권한코드';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값';
COMMENT ON COLUMN MEMBER.CREATED_AT IS '생성일';
COMMENT ON COLUMN MEMBER.UPDATED_AT IS '수정일';
COMMENT ON COLUMN MEMBER.CLASS_NO IS '반번호';

INSERT INTO MEMBER 
VALUES(SEQ_USER_NO.NEXTVAL, 'admin','admin1234!','관리자','01012345678','admin1234@gmail.com','서울특별시 강남구 테헤란로14길 6 남도빌딩','ADMIN','ACTIVE',SYSDATE,SYSDATE,NULL);

INSERT INTO MEMBER
VALUES (SEQ_USER_NO.NEXTVAL, 'counselor2928','pass2928^','정종욱','01029289121','a01029289121@gmail.com','경기도 남양주시 화도읍 비룡로110-17','COUNSELOR','ACTIVE',SYSDATE,SYSDATE,'1'); 

INSERT INTO MEMBER
VALUES (SEQ_USER_NO.NEXTVAL, 'student2928','PASS0001^','홍길동','01098765432','unk21059@naver.com','서울특별시 강남구 테헤란로14길 6 남도빌딩2F','STUDENT','ACTIVE',SYSDATE,SYSDATE,'1');

--상담사링크관리 테이블
CREATE TABLE COUNSELOR_INVITE (
  INVITE_NO NUMBER CONSTRAINT PK_INVITE_NO PRIMARY KEY,
  INVITE_NAME VARCHAR2(20) NOT NULL,
  INVITE_EMAIL VARCHAR2(100) NOT NULL,
  INVITE_TOKEN VARCHAR2(50) NOT NULL CONSTRAINT UQ_INVITE_TOKEN UNIQUE,
  INVITE_SENT_AT DATE DEFAULT SYSDATE NOT NULL,
  INVITE_EXPIRED_AT DATE DEFAULT SYSDATE + 1 NOT NULL,
  INVITE_STATUS VARCHAR2(20) CONSTRAINT CK_INVITE_STATUS CHECK ( INVITE_STATUS IN('PENDING', 'USED', 'CANCELED', 'EXPIRED')),
  USER_NO NUMBER,
  CONSTRAINT FK_INVITE_MEMBER FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_NO IS '식별번호';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_NAME IS '상담사이름';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_EMAIL IS '상담사이메일';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_TOKEN IS '토큰';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_SENT_AT IS '토큰생성시간';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_EXPIRED_AT IS '토큰만료시간';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_STATUS IS '상태';
COMMENT ON COLUMN COUNSELOR_INVITE.USER_NO IS '사용자번호';

-- 게시글 테이블
CREATE TABLE BOARD_POST (
  POST_NO NUMBER CONSTRAINT PK_POST_NO PRIMARY KEY,
  POST_TYPE VARCHAR2(10) NOT NULL,
  CATEGORY VARCHAR2(30) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  CONTENT CLOB,
  CREATED_AT DATE NOT NULL,
  UPDATED_AT DATE,
  WRITER_NO NUMBER NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL CONSTRAINT CK_POST_STATUS CHECK (STATUS IN('Y','N')),
  VIEW_COUNT NUMBER DEFAULT 0,
  CONSTRAINT FK_POST_WRITER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN BOARD_POST.POST_NO IS '게시글번호';
COMMENT ON COLUMN BOARD_POST.WRITER_NO IS '작성자회원번호';
COMMENT ON COLUMN BOARD_POST.POST_TYPE IS '게시글타입';
COMMENT ON COLUMN BOARD_POST.CATEGORY IS '게시글 카테고리';
COMMENT ON COLUMN BOARD_POST.TITLE IS '글제목';
COMMENT ON COLUMN BOARD_POST.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD_POST.CREATED_AT IS '작성일';
COMMENT ON COLUMN BOARD_POST.UPDATED_AT IS '수정일';
COMMENT ON COLUMN BOARD_POST.STATUS IS '상태값';
COMMENT ON COLUMN BOARD_POST.VIEW_COUNT IS '조회수';

-- 상담 카테고리 테이블
CREATE TABLE COUNSEL_CATEGORY (
  CATEGORY_NO NUMBER CONSTRAINT PK_CATEGORY_NO PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN COUNSEL_CATEGORY.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSEL_CATEGORY.CATEGORY_NAME IS '상담카테고리명';

INSERT INTO COUNSEL_CATEGORY VALUES(1, '취업');
INSERT INTO COUNSEL_CATEGORY VALUES(2, '진로');
INSERT INTO COUNSEL_CATEGORY VALUES(3, '수강');

-- 댓글 테이블
CREATE TABLE POST_COMMENT (
  COMMENT_NO NUMBER CONSTRAINT PK_COMMENT_NO PRIMARY KEY,
  POST_NO NUMBER NOT NULL,
  WRITER_NO NUMBER NOT NULL,
  CONTENT VARCHAR2(1000),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT CK_COMMENT_STATUS CHECK (STATUS IN ('Y','N')),
  CONSTRAINT FK_COMMENT_POST FOREIGN KEY(POST_NO) REFERENCES BOARD_POST(POST_NO)
);

COMMENT ON COLUMN POST_COMMENT.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN POST_COMMENT.POST_NO IS '게시글번호';
COMMENT ON COLUMN POST_COMMENT.WRITER_NO IS '작성자번호';
COMMENT ON COLUMN POST_COMMENT.CONTENT IS '댓글내용';
COMMENT ON COLUMN POST_COMMENT.CREATED_AT IS '생성일';
COMMENT ON COLUMN POST_COMMENT.UPDATED_AT IS '수정일';
COMMENT ON COLUMN POST_COMMENT.STATUS IS '상태값 Y/N';

-- 직원관리테이블
CREATE TABLE COUNSELOR_PROFILE (
  COUNSEL_NO NUMBER CONSTRAINT PK_COUNSEL_NO PRIMARY KEY,
  CATEGORY_NO NUMBER NOT NULL,
  PROFILE_IMG_PATH VARCHAR2(500) NOT NULL,
  BIO VARCHAR2(300),
  STATUS VARCHAR2(10) CONSTRAINT CK_STATUS CHECK (STATUS IN('ACTIVE', 'ON_LEAVE', 'RESIGNED')),
  USER_NO NUMBER,
  CONSTRAINT FK_PROFILE_MEMBER FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO),
  CONSTRAINT FK_PROFILE_CATEGORY FOREIGN KEY(CATEGORY_NO) REFERENCES COUNSEL_CATEGORY(CATEGORY_NO)
);


COMMENT ON COLUMN COUNSELOR_PROFILE.COUNSEL_NO IS '상담사번호';
COMMENT ON COLUMN COUNSELOR_PROFILE.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSELOR_PROFILE.PROFILE_IMG_PATH IS '프로필사진경로';
COMMENT ON COLUMN COUNSELOR_PROFILE.BIO IS '사원정보';
COMMENT ON COLUMN COUNSELOR_PROFILE.STATUS IS '비고';
COMMENT ON COLUMN COUNSELOR_PROFILE.USER_NO IS '사용자번호';

-- 메모 테이블
CREATE TABLE MEMBER_MEMO (
  MEMO_NO NUMBER CONSTRAINT PK_MEMO_NO PRIMARY KEY,
  USER_NO NUMBER NOT NULL,
  USER_MEMO CLOB,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  CONSTRAINT FK_MEMO_MEMBER FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN MEMBER_MEMO.MEMO_NO IS '메모번호';
COMMENT ON COLUMN MEMBER_MEMO.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER_MEMO.USER_MEMO IS '회원메모';
COMMENT ON COLUMN MEMBER_MEMO.CREATED_AT IS '메모생성일';
COMMENT ON COLUMN MEMBER_MEMO.UPDATED_AT IS '메모수정일';

-- 계정잠금 테이블
CREATE TABLE MEMBER_LOCK (
  USER_NO NUMBER CONSTRAINT PK_LOCK_USER_NO PRIMARY KEY,
  FAIL_COUNT NUMBER DEFAULT 0 NOT NULL,
  IS_LOCKED VARCHAR2(1) DEFAULT 'N' CONSTRAINT CK_IS_LOCKED NOT NULL CHECK (IS_LOCKED IN ('Y','N')),
  LOCKED_AT DATE DEFAULT SYSDATE,
  LAST_FAIL_AT DATE DEFAULT SYSDATE,
  CONSTRAINT FK_LOCK_MEMBER FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);

COMMENT ON COLUMN MEMBER_LOCK.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER_LOCK.FAIL_COUNT IS '로그인실패횟수';
COMMENT ON COLUMN MEMBER_LOCK.IS_LOCKED IS '계정잠금여부';
COMMENT ON COLUMN MEMBER_LOCK.LOCKED_AT IS '잠금발생시간';
COMMENT ON COLUMN MEMBER_LOCK.LAST_FAIL_AT IS '마지막로그인실패시간';

-- 학생 테이블
CREATE TABLE STUDENT_DETAIL (
  STUDENT_NO NUMBER CONSTRAINT PK_STUDENT_NO PRIMARY KEY,
  COUNSELOR_NO NUMBER,
  PARENT_PHONE VARCHAR2(20),
  CONSULT_STATUS VARCHAR2(1) DEFAULT 'N' CONSTRAINT CK_CONSULT_STATUS CHECK(CONSULT_STATUS IN('Y', 'N')),
  STUDENT_STATUS VARCHAR2(20) DEFAULT 'ATTENDING' CONSTRAINT CK_STUDENT_STATUS CHECK(STUDENT_STATUS IN('ATTENDING', 'ABSENT', 'DROPOUT')),
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  CONSTRAINT FK_STUDENT_COUNSELOR FOREIGN KEY (COUNSELOR_NO) REFERENCES COUNSELOR_PROFILE(COUNSEL_NO)
);

COMMENT ON COLUMN STUDENT_DETAIL.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN STUDENT_DETAIL.COUNSELOR_NO IS '담당상담사번호';
COMMENT ON COLUMN STUDENT_DETAIL.PARENT_PHONE IS '학부모연락처';
COMMENT ON COLUMN STUDENT_DETAIL.CONSULT_STATUS IS '상담진행여부';
COMMENT ON COLUMN STUDENT_DETAIL.STUDENT_STATUS IS '학생상태';
COMMENT ON COLUMN STUDENT_DETAIL.CREATED_AT IS '생성일';
COMMENT ON COLUMN STUDENT_DETAIL.UPDATED_AT IS '수정일';

-- 예약 테이블
CREATE TABLE COUNSEL_RESERVATION (
  RESERVATION_NO NUMBER CONSTRAINT PK_RESERVATION_NO PRIMARY KEY,
  STUDENT_NO NUMBER NOT NULL,
  CATEGORY_NO NUMBER NOT NULL,
  CONSULT_DATE DATE DEFAULT SYSDATE NOT NULL,
  INQUIRY_CONTENT CLOB NOT NULL,
  RESERVATION_STATUS VARCHAR2(20) DEFAULT 'RESERVED' CONSTRAINT CK_RESERVATION_STATUS CHECK(RESERVATION_STATUS IN ('APPLIED', 'CANCELED', 'RESERVED', 'COMPLETED')), 
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  COUNSEL_NO NUMBER NOT NULL,
  CONSTRAINT FK_RESERVATION_STUDENT FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT_DETAIL(STUDENT_NO),
  CONSTRAINT FK_RESERVATION_COUNSELOR FOREIGN KEY (COUNSEL_NO) REFERENCES COUNSELOR_PROFILE(COUNSEL_NO)
);

COMMENT ON COLUMN COUNSEL_RESERVATION.RESERVATION_NO IS '예약번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.CONSULT_DATE IS '상담일시';
COMMENT ON COLUMN COUNSEL_RESERVATION.INQUIRY_CONTENT IS '문의내용';
COMMENT ON COLUMN COUNSEL_RESERVATION.RESERVATION_STATUS IS '예약상태';
COMMENT ON COLUMN COUNSEL_RESERVATION.CREATED_AT IS '생성일';
COMMENT ON COLUMN COUNSEL_RESERVATION.COUNSEL_NO IS '상담사번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.UPDATED_AT IS '수정일';

-- 첨부파일게시판 테이블
CREATE TABLE FILE_ATTACHMENT (
  FILE_NO NUMBER CONSTRAINT PK_FILE_NO PRIMARY KEY,
  TARGET_NO NUMBER NOT NULL,
  TARGET_TYPE VARCHAR2(20) NOT NULL CONSTRAINT CK_TARGET_TYPE CHECK (TARGET_TYPE IN('NOTICE', 'POST')),
  ORIGIN_NAME VARCHAR2(300) NOT NULL,
  SAVE_NAME VARCHAR2(300) NOT NULL,
  FILE_PATH VARCHAR2(500) NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CONSTRAINT CK_FILE_ATTACHMENT_STATUS NOT NULL CHECK (STATUS IN ('Y', 'N')),
  CONSTRAINT FK_ATTACHMENT_BOARD FOREIGN KEY(TARGET_NO) REFERENCES BOARD_POST(POST_NO)
);

COMMENT ON COLUMN FILE_ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN FILE_ATTACHMENT.TARGET_NO IS '원본게시글식별번호';
COMMENT ON COLUMN FILE_ATTACHMENT.TARGET_TYPE IS '원본게시글타입';
COMMENT ON COLUMN FILE_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN FILE_ATTACHMENT.SAVE_NAME IS '저장파일명';
COMMENT ON COLUMN FILE_ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN FILE_ATTACHMENT.CREATED_AT IS '업로드일';
COMMENT ON COLUMN FILE_ATTACHMENT.UPDATED_AT IS '수정일';
COMMENT ON COLUMN FILE_ATTACHMENT.STATUS IS '속성';

-- 상담기록 테이블
CREATE TABLE COUNSEL_LOG (
  LOG_NO NUMBER CONSTRAINT PK_LOG_NO PRIMARY KEY,
  RESERVATION_NO NUMBER NOT NULL,
  CONTENT CLOB NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE,
  STATUS VARCHAR(1) DEFAULT 'Y' NOT NULL CONSTRAINT CK_COUNSEL_LOG_STATUS CHECK(STATUS IN('Y', 'N')),
  CONSTRAINT FK_COUNSEL_LOG_RESERVATION FOREIGN KEY(RESERVATION_NO) REFERENCES COUNSEL_RESERVATION(RESERVATION_NO)
);

COMMENT ON COLUMN COUNSEL_LOG.LOG_NO IS '상담일지번호';
COMMENT ON COLUMN COUNSEL_LOG.RESERVATION_NO IS '예약번호';
COMMENT ON COLUMN COUNSEL_LOG.CONTENT IS '상담내용';
COMMENT ON COLUMN COUNSEL_LOG.CREATED_AT IS '작성일';
COMMENT ON COLUMN COUNSEL_LOG.UPDATED_AT IS '수정일';
COMMENT ON COLUMN COUNSEL_LOG.STATUS IS '상태값';

COMMIT;