-- 직원관리 테이블 데이터 삽입 
--(userNO가 4, 6, 7, 8인 상담사 insert)
INSERT INTO COUNSELOR_PROFILE VALUES(SEQ_COUNSEL_NO.NEXTVAL, 1, '/profile/counselor1.png', '취업 상담 전문 상담사입니다.', 'ACTIVE', 4);
INSERT INTO COUNSELOR_PROFILE VALUES(SEQ_COUNSEL_NO.NEXTVAL, 2, '/profile/counselor1.png', '진로 상담 전문 상담사입니다.', 'ACTIVE', 6);
INSERT INTO COUNSELOR_PROFILE VALUES(SEQ_COUNSEL_NO.NEXTVAL, 2, '/profile/counselor1.png', '진로 상담 전문 상담사입니다.', 'ACTIVE', 7);
INSERT INTO COUNSELOR_PROFILE VALUES(SEQ_COUNSEL_NO.NEXTVAL, 3, '/profile/counselor1.png', '수강 상담 전문 상담사입니다.', 'ACTIVE', 8);


-- 학생 테이블 데이터 입력
INSERT INTO STUDENT_DETAIL VALUES(SEQ_STUDENT_NO.NEXTVAL, 3, '010-9000-1001', 'N', 'ATTENDING', SYSDATE, SYSDATE, 5);
INSERT INTO STUDENT_DETAIL VALUES(SEQ_STUDENT_NO.NEXTVAL, 4, '010-9000-1002', 'N', 'ATTENDING', SYSDATE, SYSDATE, 9);
INSERT INTO STUDENT_DETAIL VALUES(SEQ_STUDENT_NO.NEXTVAL, 5, '010-9000-1003', 'N', 'ATTENDING', SYSDATE, SYSDATE, 10);
INSERT INTO STUDENT_DETAIL VALUES(SEQ_STUDENT_NO.NEXTVAL, 6, '010-9000-1004', 'N', 'ATTENDING', SYSDATE, SYSDATE, 11);

-- MEMBER 테이블 데이터 입력
-- 상담사
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'counselor1001','Pass1001!','김상담','01011112222','kimcounselor@gmail.com','서울특별시 강남구','COUNSELOR','ACTIVE',SYSDATE,SYSDATE,1);
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'counselor1002','Pass1002!','이진로','01022223333','leecounselor@gmail.com','경기도 성남시','COUNSELOR','ACTIVE',SYSDATE,SYSDATE,1);
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'counselor1003','Pass1003!','박수강','01033334444','parkcounselor@gmail.com','인천광역시 연수구','COUNSELOR','ACTIVE',SYSDATE,SYSDATE,1);
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'student1001','Pass2001!','김철수','01044445555','student1001@gmail.com','서울특별시 송파구','STUDENT','ACTIVE',SYSDATE,SYSDATE,1);
-- 학생
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'student1002','Pass2002!','이영희','01055556666','student1002@gmail.com','경기도 수원시','STUDENT','ACTIVE',SYSDATE,SYSDATE,1);
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'student1003','Pass2003!','박민수','01066667777','student1003@gmail.com','인천광역시 남동구','STUDENT','ACTIVE',SYSDATE,SYSDATE,1);
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'student1004','Pass2004!','최지은','01077778888','student1004@gmail.com','대전광역시 서구','STUDENT','ACTIVE',SYSDATE,SYSDATE,1);
INSERT INTO MEMBER VALUES(SEQ_USER_NO.NEXTVAL, 'student1005','Pass2005!','정현우','01088889999','student1005@gmail.com','부산광역시 해운대구','STUDENT','ACTIVE',SYSDATE,SYSDATE,1);

-- 계정 잠금발생
INSERT INTO MEMBER_LOCK VALUES(1,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(2,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(3,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(4,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(5,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(6,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(7,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(8,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(9,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(10,0,'N',SYSDATE,SYSDATE);
INSERT INTO MEMBER_LOCK VALUES(11,0,'N',SYSDATE,SYSDATE);

-- 예약 테이블 데이터 삽입
-- (학생 테이블에 있는 담당 상담사는 고정, 하지만 학생은 다른 상담사에게도 상담을 받을 수 있도록)
-- STUDENT_DETAIL에 있는 상담사는 '담임 선생님' 개념으로 유지하기
-- STUDENT_DETAIL.COUNSELOR_NO : 나의 고정 담임(관리) 상담사 번호
-- COUNSEL_RESERVATION.COUNSEL_NO : 해당 회차에 실제로 상담을 진행하는 상담사 번호

-- 정종욱 상담사가 하는 홍길동 학생 취업 상담
INSERT INTO COUNSEL_RESERVATION VALUES(SEQ_RESERVATION_NO.NEXTVAL, 6, 1, TO_DATE('2026-06-10 14:00','YYYY-MM-DD HH24:MI'), '취업관련 상담', 'APPLIED', SYSDATE, SYSDATE,3);

INSERT INTO COUNSEL_RESERVATION VALUES(SEQ_RESERVATION_NO.NEXTVAL, 6, 2, TO_DATE('2026-06-15 15:00','YYYY-MM-DD HH24:MI'), '진로관련 상담', 'APPLIED', SYSDATE, SYSDATE, 4);
COMMIT;
-- 김상담 상담사가 하는 이영희 학생 진로 상담
INSERT INTO COUNSEL_RESERVATION VALUES(SEQ_RESERVATION_NO.NEXTVAL, 7, 2, TO_DATE('2026-06-11 14:00','YYYY-MM-DD HH24:MI'), '진로관련 상담', 'APPLIED', SYSDATE, SYSDATE,4);
-- 이진로 상담사가 하는 박민수 학생 진로 상담
INSERT INTO COUNSEL_RESERVATION VALUES(SEQ_RESERVATION_NO.NEXTVAL, 8, 2, TO_DATE('2026-06-12 14:00','YYYY-MM-DD HH24:MI'), '진로관련 상담', 'APPLIED', SYSDATE, SYSDATE, 5);
-- 박수강 상담사가 하는 최지은 학생 수강 상담
INSERT INTO COUNSEL_RESERVATION VALUES(SEQ_RESERVATION_NO.NEXTVAL, 9, 3, TO_DATE('2026-06-13 14:00','YYYY-MM-DD HH24:MI'), '수강관련 상담', 'APPLIED', SYSDATE, SYSDATE, 6);

-- 상담 예약 목록 출력 쿼리문
SELECT R.RESERVATION_NO,
       R.CONSULT_DATE,
       M.USER_NAME,
       C.CATEGORY_NAME,
       R.RESERVATION_STATUS
FROM COUNSEL_RESERVATION R
JOIN COUNSELOR_PROFILE CP
ON R.COUNSEL_NO = CP.COUNSEL_NO
JOIN MEMBER M
ON CP.USER_NO = M.USER_NO
JOIN COUNSEL_CATEGORY C
ON R.CATEGORY_NO = C.CATEGORY_NO;

SELECT * FROM STUDENT_DETAIL;