-- DROP SEQUENCE
DROP SEQUENCE SEQ_CATEGORY_NO;
DROP SEQUENCE SEQ_CLASS_NO;
DROP SEQUENCE SEQ_COMMENT_NO;
DROP SEQUENCE SEQ_COUNSEL_NO;
DROP SEQUENCE SEQ_FILE_NO;
DROP SEQUENCE SEQ_INVITE_NO;
DROP SEQUENCE SEQ_LOG_NO;
DROP SEQUENCE SEQ_MEMO_NO;
DROP SEQUENCE SEQ_POST_NO;
DROP SEQUENCE SEQ_PROFILE_NO;
DROP SEQUENCE SEQ_RESERVATION_NO;
DROP SEQUENCE SEQ_STUDENT_NO;
DROP SEQUENCE SEQ_USER_NO;

-- CREATE SEQUENCE
CREATE SEQUENCE SEQ_CATEGORY_NO NOCACHE;
CREATE SEQUENCE SEQ_CLASS_NO NOCACHE;
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;
CREATE SEQUENCE SEQ_COUNSEL_NO NOCACHE;
CREATE SEQUENCE SEQ_FILE_NO NOCACHE;
CREATE SEQUENCE SEQ_INVITE_NO NOCACHE;
CREATE SEQUENCE SEQ_LOG_NO NOCACHE;
CREATE SEQUENCE SEQ_MEMO_NO NOCACHE;
CREATE SEQUENCE SEQ_POST_NO NOCACHE;
CREATE SEQUENCE SEQ_PROFILE_NO NOCACHE;
CREATE SEQUENCE SEQ_RESERVATION_NO NOCACHE;
CREATE SEQUENCE SEQ_STUDENT_NO NOCACHE;
CREATE SEQUENCE SEQ_USER_NO NOCACHE;
DROP SEQUENCE SEQ_PROFILE_IMG_NO;

-- DROP TABLE
DROP TABLE COUNSEL_LOG;
DROP TABLE COUNSEL_RESERVATION;
DROP TABLE STUDENT_DETAIL;
DROP TABLE POST_COMMENT;
DROP TABLE FILE_ATTACHMENT;
DROP TABLE COUNSELOR_PROFILE;
DROP TABLE COUNSELOR_INVITE;
DROP TABLE BOARD_POST;
DROP TABLE MEMBER_MEMO;
DROP TABLE MEMBER_LOCK;
DROP TABLE MEMBER;
DROP TABLE COUNSEL_CATEGORY;
DROP TABLE CLASS;
DROP TABLE COUNSELOR_PROFIL_IMG;

CREATE TABLE COUNSELOR_PROFIL_IMG(
PROFILE_NO NUMBER PRIMARY KEY,
USER_NO NUMBER NOT NULL,
ORIGIN_NAME VARCHAR2(300) NOT NULL,
SAVE_NAME VARCHAR2(300) NOT NULL,
FILE_PATH VARCHAR2(500) NOT NULL,
UPLOADED_AT DATE DEFAULT SYSDATE,
STATUS VARCHAR2(1) DEFAULT 'Y'
);

-- CREATE CLASS
CREATE TABLE CLASS (    
    CLASS_NO NUMBER, 
    CLASS_NAME VARCHAR2(100) NOT NULL, 
    DESCRIPTION VARCHAR2(500), 
    STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    CONSTRAINT CK_CLASS_STATUS CHECK (STATUS IN('Y', 'N')), 
    CONSTRAINT PK_CLASS_NO PRIMARY KEY (CLASS_NO)
);

COMMENT ON COLUMN CLASS.CLASS_NO IS '반번호';
COMMENT ON COLUMN CLASS.CLASS_NAME IS '반이름';
COMMENT ON COLUMN CLASS.DESCRIPTION IS '반설명';
COMMENT ON COLUMN CLASS.STATUS IS '사용상태';
COMMENT ON COLUMN CLASS.CREATED_AT IS '생성일';
COMMENT ON COLUMN CLASS.UPDATED_AT IS '수정일';

-- CREATE COUNSEL_CATEGORY
CREATE TABLE COUNSEL_CATEGORY (    
    CATEGORY_NO NUMBER, 
    CATEGORY_NAME VARCHAR2(50) NOT NULL, 
    CONSTRAINT PK_CATEGORY_NO PRIMARY KEY (CATEGORY_NO)
);

COMMENT ON COLUMN COUNSEL_CATEGORY.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSEL_CATEGORY.CATEGORY_NAME IS '상담카테고리명';

-- CREATE MEMBER
CREATE TABLE MEMBER (    
    USER_NO NUMBER, 
    USER_ID VARCHAR2(50) NOT NULL, 
    USER_PWD VARCHAR2(200) NOT NULL, 
    USER_NAME VARCHAR2(20) NOT NULL, 
    PHONE VARCHAR2(20), 
    EMAIL VARCHAR2(100) NOT NULL, 
    ADDRESS VARCHAR2(300), 
    ROLE_CODE VARCHAR2(20) DEFAULT 'STUDENT' NOT NULL, 
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    CLASS_NO NUMBER, 
    CONSTRAINT CK_MEMBER_ROLE_CODE CHECK (ROLE_CODE IN('STUDENT', 'COUNSELOR', 'INSTRUCTOR', 'ADMIN')), 
    CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN('PENDING', 'ACTIVE', 'INACTIVE', 'REJECTED', 'WITHDRAWN')), 
    CONSTRAINT PK_USER_NO PRIMARY KEY (USER_NO), 
    CONSTRAINT UQ_USER_ID UNIQUE (USER_ID), 
    CONSTRAINT FK_MEMBER_CLASS FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO)
);

COMMENT ON COLUMN MEMBER.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '사용자아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '사용자비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '사용자이름';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.ROLE_CODE IS '권한코드';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값';
COMMENT ON COLUMN MEMBER.CREATED_AT IS '생성일';
COMMENT ON COLUMN MEMBER.UPDATED_AT IS '수정일';
COMMENT ON COLUMN MEMBER.CLASS_NO IS '반번호';

-- CREATE MEMBER_LOCK
CREATE TABLE MEMBER_LOCK (    
    USER_NO NUMBER, 
    FAIL_COUNT NUMBER DEFAULT 0 NOT NULL, 
    IS_LOCKED VARCHAR2(1) DEFAULT 'N' NOT NULL, 
    LOCKED_AT DATE DEFAULT SYSDATE, 
    LAST_FAIL_AT DATE DEFAULT SYSDATE, 
    CONSTRAINT CK_IS_LOCKED CHECK (IS_LOCKED IN ('Y','N')), 
    CONSTRAINT PK_LOCK_USER_NO PRIMARY KEY (USER_NO), 
    CONSTRAINT FK_LOCK_MEMBER FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

COMMENT ON COLUMN MEMBER_LOCK.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER_LOCK.FAIL_COUNT IS '로그인실패횟수';
COMMENT ON COLUMN MEMBER_LOCK.IS_LOCKED IS '계정잠금여부';
COMMENT ON COLUMN MEMBER_LOCK.LOCKED_AT IS '잠금발생시간';
COMMENT ON COLUMN MEMBER_LOCK.LAST_FAIL_AT IS '마지막로그인실패시간';

-- CREATE MEMBER_MEMO
CREATE TABLE MEMBER_MEMO (    
    MEMO_NO NUMBER, 
    USER_NO NUMBER NOT NULL, 
    USER_MEMO CLOB, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    CONSTRAINT PK_MEMO_NO PRIMARY KEY (MEMO_NO), 
    CONSTRAINT FK_MEMO_MEMBER FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

COMMENT ON COLUMN MEMBER_MEMO.MEMO_NO IS '메모번호';
COMMENT ON COLUMN MEMBER_MEMO.USER_NO IS '사용자번호';
COMMENT ON COLUMN MEMBER_MEMO.USER_MEMO IS '회원메모';
COMMENT ON COLUMN MEMBER_MEMO.CREATED_AT IS '메모생성일';
COMMENT ON COLUMN MEMBER_MEMO.UPDATED_AT IS '메모수정일';

-- CREATE BOARD_POST
CREATE TABLE BOARD_POST (    
    POST_NO NUMBER, 
    POST_TYPE VARCHAR2(10) NOT NULL, 
    CATEGORY VARCHAR2(30) NOT NULL, 
    TITLE VARCHAR2(200) NOT NULL, 
    CONTENT CLOB, 
    CREATED_AT DATE NOT NULL, 
    UPDATED_AT DATE, 
    WRITER_NO NUMBER NOT NULL, 
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL, 
    VIEW_COUNT NUMBER DEFAULT 0, 
    CONSTRAINT CK_POST_STATUS CHECK (STATUS IN('Y','N')), 
    CONSTRAINT PK_POST_NO PRIMARY KEY (POST_NO), 
    CONSTRAINT FK_POST_WRITER FOREIGN KEY (WRITER_NO) REFERENCES MEMBER (USER_NO)
);

COMMENT ON COLUMN BOARD_POST.POST_NO IS '게시글번호';
COMMENT ON COLUMN BOARD_POST.POST_TYPE IS '게시글타입';
COMMENT ON COLUMN BOARD_POST.CATEGORY IS '게시글 카테고리';
COMMENT ON COLUMN BOARD_POST.TITLE IS '글제목';
COMMENT ON COLUMN BOARD_POST.CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD_POST.CREATED_AT IS '작성일';
COMMENT ON COLUMN BOARD_POST.UPDATED_AT IS '수정일';
COMMENT ON COLUMN BOARD_POST.WRITER_NO IS '작성자회원번호';
COMMENT ON COLUMN BOARD_POST.STATUS IS '상태값';
COMMENT ON COLUMN BOARD_POST.VIEW_COUNT IS '조회수';
   
-- CREATE COUNSELOR_INVITE
CREATE TABLE COUNSELOR_INVITE (    
    INVITE_NO NUMBER, 
    INVITE_NAME VARCHAR2(20) NOT NULL, 
    INVITE_EMAIL VARCHAR2(100) NOT NULL, 
    INVITE_TOKEN VARCHAR2(50) NOT NULL, 
    INVITE_SENT_AT DATE DEFAULT SYSDATE NOT NULL, 
    INVITE_EXPIRED_AT DATE DEFAULT SYSDATE + 1 NOT NULL, 
    INVITE_STATUS VARCHAR2(20) DEFAULT 'PENDING', 
    USER_NO NUMBER, 
    CONSTRAINT CK_INVITE_STATUS CHECK (INVITE_STATUS IN('PENDING', 'USED', 'CANCELED', 'EXPIRED')), 
    CONSTRAINT PK_INVITE_NO PRIMARY KEY (INVITE_NO), 
    CONSTRAINT UQ_INVITE_TOKEN UNIQUE (INVITE_TOKEN), 
    CONSTRAINT FK_INVITE_MEMBER FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_NO IS '식별번호';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_NAME IS '상담사이름';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_EMAIL IS '상담사이메일';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_TOKEN IS '토큰';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_SENT_AT IS '토큰생성시간';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_EXPIRED_AT IS '토큰만료시간';
COMMENT ON COLUMN COUNSELOR_INVITE.INVITE_STATUS IS '상태';
COMMENT ON COLUMN COUNSELOR_INVITE.USER_NO IS '사용자번호';

-- CREATE COUNSELOR_PROFILE
CREATE TABLE COUNSELOR_PROFILE (    
    COUNSEL_NO NUMBER, 
    CATEGORY_NO NUMBER, 
    PROFILE_IMG_PATH VARCHAR2(500), 
    BIO VARCHAR2(300), 
    STATUS VARCHAR2(10), 
    USER_NO NUMBER, 
    CONSTRAINT CK_STATUS CHECK (STATUS IN('ACTIVE', 'ON_LEAVE', 'RESIGNED')), 
    CONSTRAINT PK_COUNSEL_NO PRIMARY KEY (COUNSEL_NO), 
    CONSTRAINT FK_PROFILE_MEMBER FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO), 
    CONSTRAINT FK_PROFILE_CATEGORY FOREIGN KEY (CATEGORY_NO) REFERENCES COUNSEL_CATEGORY (CATEGORY_NO)
);

COMMENT ON COLUMN COUNSELOR_PROFILE.COUNSEL_NO IS '상담사번호';
COMMENT ON COLUMN COUNSELOR_PROFILE.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSELOR_PROFILE.PROFILE_IMG_PATH IS '프로필사진경로';
COMMENT ON COLUMN COUNSELOR_PROFILE.BIO IS '사원정보';
COMMENT ON COLUMN COUNSELOR_PROFILE.STATUS IS '비고';
COMMENT ON COLUMN COUNSELOR_PROFILE.USER_NO IS '사용자번호';

-- CREATE FILE_ATTACHMENT
CREATE TABLE FILE_ATTACHMENT (    
    FILE_NO NUMBER, 
    TARGET_NO NUMBER NOT NULL, 
    TARGET_TYPE VARCHAR2(20) NOT NULL, 
    ORIGIN_NAME VARCHAR2(300) NOT NULL, 
    SAVE_NAME VARCHAR2(300) NOT NULL, 
    FILE_PATH VARCHAR2(500) NOT NULL, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL, 
    FILE_LEVEL VARCHAR2(1), 
    CONSTRAINT CK_TARGET_TYPE CHECK (TARGET_TYPE IN('NOTICE', 'POST', 'NEWS')), 
    CONSTRAINT CK_FILE_ATTACHMENT_STATUS CHECK (STATUS IN ('Y', 'N')), 
    CONSTRAINT CK_FILE_LEVEL CHECK (FILE_LEVEL IN('1', '2')), 
    CONSTRAINT PK_FILE_NO PRIMARY KEY (FILE_NO), 
    CONSTRAINT FK_ATTACHMENT_BOARD FOREIGN KEY (TARGET_NO) REFERENCES BOARD_POST (POST_NO)
);

COMMENT ON COLUMN FILE_ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN FILE_ATTACHMENT.TARGET_NO IS '원본게시글식별번호';
COMMENT ON COLUMN FILE_ATTACHMENT.TARGET_TYPE IS '원본게시글타입';
COMMENT ON COLUMN FILE_ATTACHMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN FILE_ATTACHMENT.SAVE_NAME IS '저장파일명';
COMMENT ON COLUMN FILE_ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN FILE_ATTACHMENT.CREATED_AT IS '업로드일';
COMMENT ON COLUMN FILE_ATTACHMENT.UPDATED_AT IS '수정일';
COMMENT ON COLUMN FILE_ATTACHMENT.STATUS IS '속성';
COMMENT ON COLUMN FILE_ATTACHMENT.FILE_LEVEL IS '파일레벨';

-- CREATE POST_COMMENT
CREATE TABLE POST_COMMENT (    
    COMMENT_NO NUMBER, 
    POST_NO NUMBER NOT NULL, 
    WRITER_NO NUMBER NOT NULL, 
    CONTENT VARCHAR2(1000), 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    STATUS VARCHAR2(1) DEFAULT 'Y', 
    CONSTRAINT CK_COMMENT_STATUS CHECK (STATUS IN ('Y','N')), 
    CONSTRAINT PK_COMMENT_NO PRIMARY KEY (COMMENT_NO), 
    CONSTRAINT FK_COMMENT_POST FOREIGN KEY (POST_NO) REFERENCES BOARD_POST (POST_NO)
);

COMMENT ON COLUMN POST_COMMENT.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN POST_COMMENT.POST_NO IS '게시글번호';
COMMENT ON COLUMN POST_COMMENT.WRITER_NO IS '작성자번호';
COMMENT ON COLUMN POST_COMMENT.CONTENT IS '댓글내용';
COMMENT ON COLUMN POST_COMMENT.CREATED_AT IS '생성일';
COMMENT ON COLUMN POST_COMMENT.UPDATED_AT IS '수정일';
COMMENT ON COLUMN POST_COMMENT.STATUS IS '상태값 Y/N';

-- CREATE STUDENT_DETAIL
CREATE TABLE STUDENT_DETAIL (    
    STUDENT_NO NUMBER, 
    COUNSELOR_NO NUMBER, 
    PARENT_PHONE VARCHAR2(20), 
    STUDENT_STATUS VARCHAR2(20) DEFAULT 'ATTENDING', 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    USER_NO NUMBER, 
    CONSTRAINT CK_STUDENT_STATUS CHECK (STUDENT_STATUS IN('ATTENDING', 'ABSENT', 'DROPOUT')), 
    CONSTRAINT PK_STUDENT_NO PRIMARY KEY (STUDENT_NO), 
    CONSTRAINT FK_STUDENT_COUNSELOR FOREIGN KEY (COUNSELOR_NO) REFERENCES COUNSELOR_PROFILE (COUNSEL_NO), 
    CONSTRAINT FK_STUDENT_MEMBER FOREIGN KEY (USER_NO) REFERENCES MEMBER (USER_NO)
);

COMMENT ON COLUMN STUDENT_DETAIL.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN STUDENT_DETAIL.COUNSELOR_NO IS '담당상담사번호';
COMMENT ON COLUMN STUDENT_DETAIL.PARENT_PHONE IS '학부모연락처';
COMMENT ON COLUMN STUDENT_DETAIL.STUDENT_STATUS IS '학생상태';
COMMENT ON COLUMN STUDENT_DETAIL.CREATED_AT IS '생성일';
COMMENT ON COLUMN STUDENT_DETAIL.UPDATED_AT IS '수정일';

-- CREATE COUNSEL_RESERVATION
CREATE TABLE COUNSEL_RESERVATION (    
    RESERVATION_NO NUMBER, 
    STUDENT_NO NUMBER NOT NULL, 
    CATEGORY_NO NUMBER NOT NULL, 
    CONSULT_DATE DATE DEFAULT SYSDATE NOT NULL, 
    INQUIRY_CONTENT CLOB NOT NULL, 
    RESERVATION_STATUS VARCHAR2(20) DEFAULT 'RESERVED', 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    COUNSEL_NO NUMBER NOT NULL, 
    CONSTRAINT CK_RESERVATION_STATUS CHECK (RESERVATION_STATUS IN ('APPLIED', 'CANCELED', 'RESERVED', 'COMPLETED', 'REJECTED')), 
    CONSTRAINT PK_RESERVATION_NO PRIMARY KEY (RESERVATION_NO), 
    CONSTRAINT FK_RESERVATION_STUDENT FOREIGN KEY (STUDENT_NO) REFERENCES STUDENT_DETAIL (STUDENT_NO), 
    CONSTRAINT FK_RESERVATION_COUNSELOR FOREIGN KEY (COUNSEL_NO) REFERENCES COUNSELOR_PROFILE (COUNSEL_NO)
);

COMMENT ON COLUMN COUNSEL_RESERVATION.RESERVATION_NO IS '예약번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.STUDENT_NO IS '학생번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.CATEGORY_NO IS '상담카테고리번호';
COMMENT ON COLUMN COUNSEL_RESERVATION.CONSULT_DATE IS '상담일시';
COMMENT ON COLUMN COUNSEL_RESERVATION.INQUIRY_CONTENT IS '문의내용';
COMMENT ON COLUMN COUNSEL_RESERVATION.RESERVATION_STATUS IS '예약상태';
COMMENT ON COLUMN COUNSEL_RESERVATION.CREATED_AT IS '생성일';
COMMENT ON COLUMN COUNSEL_RESERVATION.UPDATED_AT IS '수정일';
COMMENT ON COLUMN COUNSEL_RESERVATION.COUNSEL_NO IS '상담사번호';

-- CREATE COUNSEL_LOG
CREATE TABLE COUNSEL_LOG (    
    LOG_NO NUMBER, 
    RESERVATION_NO NUMBER NOT NULL, 
    CONTENT CLOB NOT NULL, 
    CREATED_AT DATE DEFAULT SYSDATE NOT NULL, 
    UPDATED_AT DATE DEFAULT SYSDATE, 
    STATUS VARCHAR2(1) DEFAULT 'Y' NOT NULL, 
    CONSTRAINT CK_COUNSEL_LOG_STATUS CHECK (STATUS IN('Y', 'N')), 
    CONSTRAINT PK_LOG_NO PRIMARY KEY (LOG_NO), 
    CONSTRAINT FK_COUNSEL_LOG_RESERVATION FOREIGN KEY (RESERVATION_NO) REFERENCES COUNSEL_RESERVATION (RESERVATION_NO)
);

COMMENT ON COLUMN COUNSEL_LOG.LOG_NO IS '상담일지번호';
COMMENT ON COLUMN COUNSEL_LOG.RESERVATION_NO IS '예약번호';
COMMENT ON COLUMN COUNSEL_LOG.CONTENT IS '상담내용';
COMMENT ON COLUMN COUNSEL_LOG.CREATED_AT IS '작성일';
COMMENT ON COLUMN COUNSEL_LOG.UPDATED_AT IS '수정일';
COMMENT ON COLUMN COUNSEL_LOG.STATUS IS '상태값';

-- INSERT CLASS
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'A반','2026년 5월 20일에 개설한 반입니다','Y',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'B반','2026년 5월 25일에 개설한 반입니다','Y',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'C반','2026년 5월 29일에 개설한 반입니다','Y',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'D반','2026년 6월 1일에 개설한 반입니다','N',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'AWS DevOps 1기','클라우드 기반 DevOps 풀스택 과정','Y',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'Java Backend 1기','자바 백엔드 개발자 과정','Y',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));
INSERT INTO CLASS (CLASS_NO,CLASS_NAME,DESCRIPTION,STATUS,CREATED_AT,UPDATED_AT) VALUES (SEQ_CLASS_NO.NEXTVAL,'Frontend Basic 1기','프론트엔드 기초 과정','Y',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'));

-- INSERT COUNSEL_CATEGORY
INSERT INTO COUNSEL_CATEGORY (CATEGORY_NO,CATEGORY_NAME) values (SEQ_CATEGORY_NO.NEXTVAL,'취업');
INSERT INTO COUNSEL_CATEGORY (CATEGORY_NO,CATEGORY_NAME) values (SEQ_CATEGORY_NO.NEXTVAL,'진로');
INSERT INTO COUNSEL_CATEGORY (CATEGORY_NO,CATEGORY_NAME) values (SEQ_CATEGORY_NO.NEXTVAL,'수강');

-- INSERT MEMBER, MEMBER_LOCK
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) values (SEQ_USER_NO.NEXTVAL,'admin','$2a$10$VRCL8htW2sJVPmOjqXqlx.MMsV6zl2CpmrcI3r586tN/xAYzm4rmC','관리자','01012345678','serominsockji9n9@gmail.com','서울특별시 강남구 테헤란로14길 6 남도빌딩','ADMIN','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/11','RR/MM/DD'),null);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) values (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) values (SEQ_USER_NO.NEXTVAL,'counselor2928','$2a$10$3NV7wjOuyTeFUp7oE426luK9U5czV8NryZER2yZbxE0ntdTt2zXnO','정취업','01029289121','a01029289121@gmail.com','경기도 남양주시 화도읍 비룡로110-17','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) values (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) values (SEQ_USER_NO.NEXTVAL,'student2928','$2a$10$NTizvJzmWDWh0MwCnls1neQ4MwhMWHQIqMvk7nnCIYhCjAV6/Q4p.','홍길동','01098765432','unk21059@naver.com','서울특별시 강남구 테헤란로14길 6 남도빌딩2F','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'counselor1001','$2a$10$lS8jDfzJ7vEKAfm9mwsaE.HOHlAoDqUFKM2hQggcPVSKN0G47VIlC','박진로','01011112222','kimcounselor@gmail.com','서울특별시 강남구','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),2);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'counselor1002','$2a$10$OYgUdFY.tQhK1n2kIt.EVOc6msYDsNlQ6FL25nalQNSk9rEGWK6N2','이진로','01022223333','leecounselor@gmail.com','경기도 성남시','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),3);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'counselor1003','$2a$10$DuXvYKEXM.Lp3oy20ENzUu2WytTsXat5tyAZej//5T4Ae.NinIRFO','박수강','01033334444','parkcounselor@gmail.com','인천광역시 연수구','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),4);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student1001','$2a$10$72R3JMK2/lPOc2MPnwDidesGbK/bqOZgEjLzfk3is6ckHqnMvTiGS','김철수','01044445555','student1001@gmail.com','서울특별시 송파구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student1002','$2a$10$gNsCIdbm4IwPpRYtVNnSpeI3FhNDS.Znf0tcgL3QnppLdj/iCq6Gq','이영희','01055556666','student1002@gmail.com','경기도 수원시','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student1003','$2a$10$3IwEfBVALuew6apMgMLVeuCkoUze86Qsy0KkabQQRY320jY1ZD5C.','박민수','01066667777','student1003@gmail.com','인천광역시 남동구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student1004','$2a$10$8RF5xD2e04Te7mAPahl0tOgsNRTT2B.X7Q0RPCoTlf/kUfb8bd1Pi','최지은','01077778888','student1004@gmail.com','대전광역시 서구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student1005','$2a$10$xVLW3Tosphg/gebPQT6uau7wtjGn1j6dqIJ2ZCcyhvRca0.diMkUK','정현우','01088889999','student1005@gmail.com','부산광역시 해운대구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'admin01','$2a$10$Yxa7j0wNl8nTqpL2PAJAAO/lc.E5H1qIj4UCG6s51j9m2AO47Zvh2','지관리','01000000001','admin01@knowhow.com','서울시 강남구','ADMIN','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),null);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'instructor01','$2a$10$4io0LhkKxhYsZTN.iFcHG.drDlItmRl3M2vkfWeOYlisVlxgGQFx2','박강사','01000000002','instructor01@knowhow.com','서울시 서초구','INSTRUCTOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'counselor01','$2a$10$/YPB4SsFnIgWZK4NUj.CkeKGXvW6jWjY2btn8sTkEq3.3/b3P33QS','최취업','01010000001','counselor01@knowhow.com','서울시 송파구','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),5);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'counselor02','$2a$10$jCfM9Ha6zQX0/4XQ4NNSxO8j5zIdsgZM5mftqPI5nbKYHaa6zYv2m','김진로','01010000002','counselor02@knowhow.com','서울시 마포구','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),6);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'counselor03','$2a$10$izADmDj96tF.6nR6Lw.Q6eDVvH6wGOV2VMDlfE.nLS1aBS7HcLvO.','최수강','01010000003','counselor03@knowhow.com','경기도 성남시','COUNSELOR','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),7);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student01','$2a$10$lMI0jdA/rpg7W4F1f8c7MOByIbhGVtpB5GTtn6rvExavdOjd6.a1y','홍학생','01020000001','student01@test.com','경기도 여주시','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),4);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student02','$2a$10$HJZ35QM0TcFEqazSmHgdBOCu9c9nm5kND01WlZ4xcudMKtJhssLh2','김민지','01020000002','student02@test.com','경기도 이천시','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student03','$2a$10$E.E6m6O88Xyzz3p3uqQYG.fQySLm2kcX3AOIYWZfiorS/r.GXAMaW','이준호','01020000003','student03@test.com','서울시 강동구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),2);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student04','$2a$10$.RVMSXWjl5WwD2Dsd3ORputJa6YIGmxPGh.qIbvCfKUSHish7lKS.','박서연','01020000004','student04@test.com','서울시 노원구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student05','$2a$10$MjeXeoHvJiFnXSOsKVuAQug4HMO7PNt1jwtBJ3mylirUS99jhlf9m','최도윤','01020000005','student05@test.com','인천시 부평구','STUDENT','ACTIVE',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),3);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'hd82hd82','$2a$10$3wDy4dZa.GFnJFlzrxz8JOPsLMgWDcUy9Vbj3VKoBx671MMvf2GUS','한학생',null,'minsuck2581@naver.com',null,'STUDENT','ACTIVE',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),1);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'dfjdsklj987298','$2a$10$Zw29QNOwFBLwA20UPQlCYue69zesl6vENhz8VRpSpli1srGD/zqHO','구학생',null,'fffff@ffff',null,'STUDENT','PENDING',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),null);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'student021','$2a$10$job14Md6oSl35Y73QwiG/eugcfdq/zoo2.2v0PjtXxbCgNmxj2D5C','지민석',null,'minsuck2581@naver.coms',null,'STUDENT','PENDING',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),null);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);
INSERT INTO MEMBER (USER_NO,USER_ID,USER_PWD,USER_NAME,PHONE,EMAIL,ADDRESS,ROLE_CODE,STATUS,CREATED_AT,UPDATED_AT,CLASS_NO) VALUES (SEQ_USER_NO.NEXTVAL,'qqqqqqqq1','$2a$10$FbZ22vr5BfMh9wIPzRf9o.LezlJnozowzPnw1c8VB19R.m.dQv9ey','반학생',null,'asd@asd',null,'STUDENT','REJECTED',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),null);
INSERT INTO MEMBER_LOCK (USER_NO,FAIL_COUNT,IS_LOCKED,LOCKED_AT,LAST_FAIL_AT) VALUES (SEQ_USER_NO.CURRVAL,0,'N',null,null);

-- INSERT BOARD, FILE_ATTACHMENT, POST_COMMENT
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','자유','프로젝트 질문 있습니다',to_date('26/06/01','RR/MM/DD'),null,17,'Y',12);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','질문','Git 충돌 해결 방법',to_date('26/06/02','RR/MM/DD'),null,18,'Y',30);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','후기','상담 후기 남깁니다',to_date('26/06/03','RR/MM/DD'),null,19,'Y',8);
INSERT INTO POST_COMMENT (COMMENT_NO,POST_NO,WRITER_NO,CONTENT,CREATED_AT,UPDATED_AT,STATUS) VALUES (SEQ_COMMENT_NO.NEXTVAL,SEQ_POST_NO.CURRVAL,13,'에러 메시지와 실행한 명령어를 같이 올려주세요.',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),'Y');
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','1번째 게시글입니다.',to_date('26/03/29','RR/MM/DD'),null,7,'Y',151);
INSERT INTO FILE_ATTACHMENT (FILE_NO,TARGET_NO,TARGET_TYPE,ORIGIN_NAME,SAVE_NAME,FILE_PATH,CREATED_AT,UPDATED_AT,STATUS,FILE_LEVEL) VALUES (SEQ_FILE_NO.NEXTVAL,SEQ_POST_NO.CURRVAL,'STUDENT','git_error.png','202606_git_error_001.png','/resources/upload/post/',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),'Y',null);
INSERT INTO POST_COMMENT (COMMENT_NO,POST_NO,WRITER_NO,CONTENT,CREATED_AT,UPDATED_AT,STATUS) VALUES (SEQ_COMMENT_NO.NEXTVAL,SEQ_POST_NO.CURRVAL,12,'pull 받은 뒤 다시 확인해보세요.',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),'Y');
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','2번째 게시글입니다.',to_date('26/02/12','RR/MM/DD'),null,7,'Y',209);
INSERT INTO POST_COMMENT (COMMENT_NO,POST_NO,WRITER_NO,CONTENT,CREATED_AT,UPDATED_AT,STATUS) VALUES (SEQ_COMMENT_NO.NEXTVAL,SEQ_POST_NO.CURRVAL,17,'후기 감사합니다.',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),'Y');
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','3번째 게시글입니다.',to_date('26/04/16','RR/MM/DD'),null,9,'Y',339);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','4번째 게시글입니다.',to_date('26/04/30','RR/MM/DD'),null,10,'Y',139);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','5번째 게시글입니다.',to_date('26/02/25','RR/MM/DD'),null,7,'Y',163);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','6번째 게시글입니다.',to_date('26/04/27','RR/MM/DD'),null,8,'Y',415);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','7번째 게시글입니다.',to_date('26/03/25','RR/MM/DD'),null,9,'Y',333);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','8번째 게시글입니다.',to_date('26/05/12','RR/MM/DD'),null,10,'Y',255);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','9번째 게시글입니다.',to_date('26/04/25','RR/MM/DD'),null,7,'Y',463);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','10번째 게시글입니다.',to_date('26/03/08','RR/MM/DD'),null,8,'Y',218);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','11번째 게시글입니다.',to_date('26/04/18','RR/MM/DD'),null,9,'Y',132);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','12번째 게시글입니다.',to_date('26/05/17','RR/MM/DD'),null,10,'Y',281);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','13번째 게시글입니다.',to_date('26/05/09','RR/MM/DD'),null,9,'Y',446);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','14번째 게시글입니다.',to_date('26/03/18','RR/MM/DD'),null,10,'Y',339);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','15번째 게시글입니다.',to_date('26/05/24','RR/MM/DD'),null,7,'Y',124);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','16번째 게시글입니다.',to_date('26/02/16','RR/MM/DD'),null,7,'Y',286);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','17번째 게시글입니다.',to_date('26/05/25','RR/MM/DD'),null,7,'Y',177);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','18번째 게시글입니다.',to_date('26/03/20','RR/MM/DD'),null,7,'Y',217);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','19번째 게시글입니다.',to_date('26/03/03','RR/MM/DD'),null,7,'Y',150);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','20번째 게시글입니다.',to_date('26/03/25','RR/MM/DD'),null,7,'Y',267);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','21번째 게시글입니다.',to_date('26/03/22','RR/MM/DD'),null,7,'Y',169);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','22번째 게시글입니다.',to_date('26/02/11','RR/MM/DD'),null,8,'Y',31);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','23번째 게시글입니다.',to_date('26/03/03','RR/MM/DD'),null,9,'Y',447);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','24번째 게시글입니다.',to_date('26/02/24','RR/MM/DD'),null,10,'Y',340);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','25번째 게시글입니다.',to_date('26/05/21','RR/MM/DD'),null,7,'Y',179);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','26번째 게시글입니다.',to_date('26/02/08','RR/MM/DD'),null,7,'Y',382);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','27번째 게시글입니다.',to_date('26/02/18','RR/MM/DD'),null,7,'Y',457);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','28번째 게시글입니다.',to_date('26/05/04','RR/MM/DD'),null,7,'Y',197);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','29번째 게시글입니다.',to_date('26/02/06','RR/MM/DD'),null,7,'Y',159);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','30번째 게시글입니다.',to_date('26/03/18','RR/MM/DD'),null,7,'Y',45);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','31번째 게시글입니다.',to_date('26/03/26','RR/MM/DD'),null,7,'Y',321);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','32번째 게시글입니다.',to_date('26/02/11','RR/MM/DD'),null,8,'Y',81);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','33번째 게시글입니다.',to_date('26/03/20','RR/MM/DD'),null,9,'Y',321);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','34번째 게시글입니다.',to_date('26/04/10','RR/MM/DD'),null,10,'Y',354);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','35번째 게시글입니다.',to_date('26/04/20','RR/MM/DD'),null,7,'Y',398);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','36번째 게시글입니다.',to_date('26/04/13','RR/MM/DD'),null,7,'Y',390);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','37번째 게시글입니다.',to_date('26/04/12','RR/MM/DD'),null,7,'Y',141);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','38번째 게시글입니다.',to_date('26/03/25','RR/MM/DD'),null,7,'Y',11);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','39번째 게시글입니다.',to_date('26/05/01','RR/MM/DD'),null,7,'Y',34);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','40번째 게시글입니다.',to_date('26/04/20','RR/MM/DD'),null,7,'Y',351);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','41번째 게시글입니다.',to_date('26/02/19','RR/MM/DD'),null,7,'Y',112);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','42번째 게시글입니다.',to_date('26/05/16','RR/MM/DD'),null,8,'Y',157);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','43번째 게시글입니다.',to_date('26/04/25','RR/MM/DD'),null,9,'Y',471);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','44번째 게시글입니다.',to_date('26/03/29','RR/MM/DD'),null,10,'Y',14);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','45번째 게시글입니다.',to_date('26/03/03','RR/MM/DD'),null,7,'Y',49);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','46번째 게시글입니다.',to_date('26/04/14','RR/MM/DD'),null,7,'Y',192);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','47번째 게시글입니다.',to_date('26/05/16','RR/MM/DD'),null,7,'Y',296);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','48번째 게시글입니다.',to_date('26/04/12','RR/MM/DD'),null,7,'Y',17);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','49번째 게시글입니다.',to_date('26/04/10','RR/MM/DD'),null,7,'Y',421);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','50번째 게시글입니다.',to_date('26/05/07','RR/MM/DD'),null,7,'Y',284);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','51번째 게시글입니다.',to_date('26/04/12','RR/MM/DD'),null,7,'Y',203);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','52번째 게시글입니다.',to_date('26/03/10','RR/MM/DD'),null,7,'Y',284);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','53번째 게시글입니다.',to_date('26/03/19','RR/MM/DD'),null,7,'Y',326);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','54번째 게시글입니다.',to_date('26/04/21','RR/MM/DD'),null,7,'Y',59);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','55번째 게시글입니다.',to_date('26/04/17','RR/MM/DD'),null,7,'Y',466);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','56번째 게시글입니다.',to_date('26/05/10','RR/MM/DD'),null,7,'Y',470);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','57번째 게시글입니다.',to_date('26/02/14','RR/MM/DD'),null,7,'Y',44);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','58번째 게시글입니다.',to_date('26/02/09','RR/MM/DD'),null,7,'Y',320);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','59번째 게시글입니다.',to_date('26/03/26','RR/MM/DD'),null,7,'Y',64);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','60번째 게시글입니다.',to_date('26/04/11','RR/MM/DD'),null,7,'Y',30);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','62번째 게시글입니다.',to_date('26/02/26','RR/MM/DD'),null,8,'Y',107);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','63번째 게시글입니다.',to_date('26/02/27','RR/MM/DD'),null,9,'Y',202);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','64번째 게시글입니다.',to_date('26/03/08','RR/MM/DD'),null,10,'Y',382);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','65번째 게시글입니다.',to_date('26/05/24','RR/MM/DD'),null,7,'Y',184);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','66번째 게시글입니다.',to_date('26/05/09','RR/MM/DD'),null,7,'Y',162);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','67번째 게시글입니다.',to_date('26/02/06','RR/MM/DD'),null,7,'Y',108);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','68번째 게시글입니다.',to_date('26/02/16','RR/MM/DD'),null,7,'Y',87);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','69번째 게시글입니다.',to_date('26/04/10','RR/MM/DD'),null,7,'Y',205);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','70번째 게시글입니다.',to_date('26/02/27','RR/MM/DD'),null,7,'Y',253);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','71번째 게시글입니다.',to_date('26/03/01','RR/MM/DD'),null,7,'Y',31);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','72번째 게시글입니다.',to_date('26/02/23','RR/MM/DD'),null,8,'Y',481);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','73번째 게시글입니다.',to_date('26/03/04','RR/MM/DD'),null,9,'Y',446);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','74번째 게시글입니다.',to_date('26/05/26','RR/MM/DD'),null,10,'Y',453);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','75번째 게시글입니다.',to_date('26/04/24','RR/MM/DD'),null,7,'Y',101);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','76번째 게시글입니다.',to_date('26/02/13','RR/MM/DD'),null,7,'Y',39);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','77번째 게시글입니다.',to_date('26/03/31','RR/MM/DD'),null,7,'Y',75);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','78번째 게시글입니다.',to_date('26/02/06','RR/MM/DD'),null,7,'Y',262);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','79번째 게시글입니다.',to_date('26/04/18','RR/MM/DD'),null,7,'Y',407);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','80번째 게시글입니다.',to_date('26/02/08','RR/MM/DD'),null,7,'Y',188);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','81번째 게시글입니다.',to_date('26/05/12','RR/MM/DD'),null,7,'Y',124);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','82번째 게시글입니다.',to_date('26/05/24','RR/MM/DD'),null,7,'Y',29);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','83번째 게시글입니다.',to_date('26/03/13','RR/MM/DD'),null,7,'Y',81);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','84번째 게시글입니다.',to_date('26/04/08','RR/MM/DD'),null,7,'Y',11);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','85번째 게시글입니다.',to_date('26/03/05','RR/MM/DD'),null,7,'Y',270);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','86번째 게시글입니다.',to_date('26/05/08','RR/MM/DD'),null,7,'Y',311);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','87번째 게시글입니다.',to_date('26/05/15','RR/MM/DD'),null,7,'Y',11);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','88번째 게시글입니다.',to_date('26/05/06','RR/MM/DD'),null,7,'Y',145);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','89번째 게시글입니다.',to_date('26/05/17','RR/MM/DD'),null,7,'Y',164);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','90번째 게시글입니다.',to_date('26/02/14','RR/MM/DD'),null,7,'Y',277);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','91번째 게시글입니다.',to_date('26/02/21','RR/MM/DD'),null,7,'Y',371);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','92번째 게시글입니다.',to_date('26/04/24','RR/MM/DD'),null,8,'Y',321);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','93번째 게시글입니다.',to_date('26/05/03','RR/MM/DD'),null,9,'Y',146);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','94번째 게시글입니다.',to_date('26/04/04','RR/MM/DD'),null,10,'Y',387);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','95번째 게시글입니다.',to_date('26/05/26','RR/MM/DD'),null,7,'Y',161);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','96번째 게시글입니다.',to_date('26/02/07','RR/MM/DD'),null,7,'Y',217);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','97번째 게시글입니다.',to_date('26/05/22','RR/MM/DD'),null,7,'Y',304);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','98번째 게시글입니다.',to_date('26/02/13','RR/MM/DD'),null,7,'Y',405);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','99번째 게시글입니다.',to_date('26/05/18','RR/MM/DD'),null,7,'Y',222);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','100번째 게시글입니다.',to_date('26/03/08','RR/MM/DD'),null,7,'Y',404);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','101번째 게시글입니다.',to_date('26/02/06','RR/MM/DD'),null,7,'Y',412);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','입학상담','102번째 게시글입니다.',to_date('26/05/18','RR/MM/DD'),null,8,'Y',362);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'STUDENT','취업상담','103번째 게시글입니다.',to_date('26/04/14','RR/MM/DD'),null,9,'Y',256);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'NEWS','NEWS','학원소식 관리 끝',to_date('26/06/09','RR/MM/DD'),to_date('26/06/10','RR/MM/DD'),1,'Y',0);
INSERT INTO FILE_ATTACHMENT (FILE_NO,TARGET_NO,TARGET_TYPE,ORIGIN_NAME,SAVE_NAME,FILE_PATH,CREATED_AT,UPDATED_AT,STATUS,FILE_LEVEL) VALUES (SEQ_FILE_NO.NEXTVAL,SEQ_POST_NO.CURRVAL,'NEWS','bono.jpg','202606_bono.jpg','/resources/upload/news/',to_date('26/06/09','RR/MM/DD'),to_date('26/06/09','RR/MM/DD'),'Y','1');
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'NOTICE','NOTICE','ㅁㄴㅇㄹ',to_date('26/06/10','RR/MM/DD'),null,1,'Y',0);
INSERT INTO BOARD_POST (POST_NO,POST_TYPE,CATEGORY,TITLE,CREATED_AT,UPDATED_AT,WRITER_NO,STATUS,VIEW_COUNT) VALUES (SEQ_POST_NO.NEXTVAL,'NOTICE','NOTICE','공지사항 관리 끝',to_date('26/06/09','RR/MM/DD'),null,1,'Y',0);
INSERT INTO FILE_ATTACHMENT (FILE_NO,TARGET_NO,TARGET_TYPE,ORIGIN_NAME,SAVE_NAME,FILE_PATH,CREATED_AT,UPDATED_AT,STATUS,FILE_LEVEL) VALUES (SEQ_FILE_NO.NEXTVAL,SEQ_POST_NO.CURRVAL,'NOTICE','kuromi.png','202606_kuromi.png','/resources/upload/notice/',to_date('26/06/09','RR/MM/DD'),to_date('26/06/09','RR/MM/DD'),'Y',null);

-- INSERT COUNSELOR_INVITE
INSERT INTO COUNSELOR_INVITE (INVITE_NO,INVITE_NAME,INVITE_EMAIL,INVITE_TOKEN,INVITE_SENT_AT,INVITE_EXPIRED_AT,INVITE_STATUS,USER_NO) VALUES (SEQ_INVITE_NO.NEXTVAL,'정초대','invite01@knowhow.com','TOKEN_INVITE_001',to_date('26/06/04','RR/MM/DD'),to_date('26/06/05','RR/MM/DD'),'PENDING',null);
INSERT INTO COUNSELOR_INVITE (INVITE_NO,INVITE_NAME,INVITE_EMAIL,INVITE_TOKEN,INVITE_SENT_AT,INVITE_EXPIRED_AT,INVITE_STATUS,USER_NO) VALUES (SEQ_INVITE_NO.NEXTVAL,'최취업','counselor01@knowhow.com','TOKEN_INVITE_002',to_date('26/06/04','RR/MM/DD'),to_date('26/06/05','RR/MM/DD'),'USED',14);

-- INSERT COUNSELOR_PROFILE
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,1,'/profile/counselor1.png','취업 상담 전문 상담사입니다.','ACTIVE',2);
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,2,'/profile/counselor1.png','진로 상담 전문 상담사입니다.','ACTIVE',4);
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,2,'/profile/counselor1.png','진로 상담 전문 상담사입니다.','ACTIVE',5);
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,3,'/profile/counselor1.png','수강 상담 전문 상담사입니다.','ACTIVE',6);
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,1,'/resources/profile/counselor01.jpg','취업 상담 전문 상담사입니다.','ACTIVE',14);
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,2,'/resources/profile/counselor02.jpg','진로 설계와 학습 방향 상담을 담당합니다.','ACTIVE',15);
INSERT INTO COUNSELOR_PROFILE (COUNSEL_NO,CATEGORY_NO,PROFILE_IMG_PATH,BIO,STATUS,USER_NO) VALUES (SEQ_COUNSEL_NO.NEXTVAL,3,'/resources/profile/counselor03.jpg','수강 과정 및 커리큘럼 상담을 담당합니다.','ON_LEAVE',16);

--  INSERT STUDENT_DETAIL
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,'010-9000-1001','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),3);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,'010-9000-1002','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),7);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,'010-9000-1003','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),8);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,'010-9000-1004','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),9);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,'010-9000-0001','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),10);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,'010-9000-0002','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),11);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,4,'010-9000-0003','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),17);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,null,'ATTENDING',to_date('26/06/11','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),18);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,2,'010-9000-0005','ATTENDING',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),19);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,null,'ATTENDING',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),20);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,3,null,'ATTENDING',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),21);
INSERT INTO STUDENT_DETAIL (STUDENT_NO,COUNSELOR_NO,PARENT_PHONE,STUDENT_STATUS,CREATED_AT,UPDATED_AT,USER_NO) VALUES (SEQ_STUDENT_NO.NEXTVAL,1,null,'ATTENDING',to_date('26/06/12','RR/MM/DD'),to_date('26/06/12','RR/MM/DD'),22);

-- INSERT COUNSEL_RESERVATION, COUNSEL_LOG
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,1,1,to_date('26/06/10','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,2,1,to_date('26/06/15','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,3,1,to_date('26/06/11','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,4,1,to_date('26/06/12','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_LOG (LOG_NO,RESERVATION_NO,CONTENT,CREATED_AT,UPDATED_AT,STATUS) VALUES (SEQ_LOG_NO.NEXTVAL,SEQ_RESERVATION_NO.CURRVAL,'여기에 상담 진행 내용을 입력합니다.',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),'Y');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,5,1,to_date('26/06/13','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,6,1,to_date('26/06/05','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,7,3,to_date('26/06/06','RR/MM/DD'),'RESERVED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),4,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,8,1,to_date('26/06/07','RR/MM/DD'),'APPLIED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,9,2,to_date('26/06/03','RR/MM/DD'),'COMPLETED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),2,'여기에 상담 문의 내용을 입력합니다.');
INSERT INTO COUNSEL_RESERVATION (RESERVATION_NO,STUDENT_NO,CATEGORY_NO,CONSULT_DATE,RESERVATION_STATUS,CREATED_AT,UPDATED_AT,COUNSEL_NO,INQUIRY_CONTENT) VALUES (SEQ_RESERVATION_NO.NEXTVAL,10,1,to_date('26/06/09','RR/MM/DD'),'CANCELED',to_date('26/06/04','RR/MM/DD'),to_date('26/06/04','RR/MM/DD'),1,'여기에 상담 문의 내용을 입력합니다.');
COMMIT;